#!/usr/bin/env node
// Regenerate apps/lingxi/src/data/superseded-clips.json from git history.
//
//   node --experimental-strip-types scripts/superseded-clips.mjs
//
// Every version of every built-in clip that git has ever held for actions.json - and the one in
// HEAD, if the working tree has since changed it - is fingerprinted, and each fingerprint that
// differs from the clip's CURRENT version is recorded. At load time a custom library clip that
// matches one of these is an untouched copy of an old default and follows the new one (see
// apps/lingxi/src/anim/clip-history.ts).
//
// Run it in the same commit as any change to a built-in clip. test/clip-history.test.mjs fails
// until you do, because a clip retuned without it never reaches anyone who has a custom library.
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { clipFingerprint } from '../apps/lingxi/src/anim/clip-history.ts';

const root = fileURLToPath(new URL('..', import.meta.url));
const LIBRARY = 'apps/lingxi/src/data/actions.json';
const OUT = 'apps/lingxi/src/data/superseded-clips.json';

const git = (...args) => spawnSync('git', args, { cwd: root, encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 });

/** Every committed version of the library, oldest first, plus HEAD. */
export function historicalLibraries() {
  const log = git('log', '--format=%H', '--', LIBRARY);
  if (log.status !== 0) return null;
  const commits = [...new Set(['HEAD', ...log.stdout.trim().split('\n').filter(Boolean)])];
  const libraries = [];
  for (const commit of commits) {
    const shown = git('show', `${commit}:${LIBRARY}`);
    if (shown.status === 0) libraries.push({ commit, actions: JSON.parse(shown.stdout).actions });
  }
  return libraries;
}

export function supersededFrom(current, libraries) {
  const now = new Map(current.map((clip) => [clip.id, clipFingerprint(clip)]));
  const clips = {};
  for (const { actions } of libraries) {
    for (const clip of actions) {
      const print = clipFingerprint(clip);
      if (!now.has(clip.id) || now.get(clip.id) === print) continue;
      (clips[clip.id] ??= new Set()).add(print);
    }
  }
  return Object.fromEntries(Object.keys(clips).sort().map((id) => [id, [...clips[id]].sort()]));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const libraries = historicalLibraries();
  if (!libraries) {
    console.error('git history unavailable - run this from a clone');
    process.exit(1);
  }
  const current = JSON.parse(readFileSync(`${root}/${LIBRARY}`, 'utf8')).actions;
  const clips = supersededFrom(current, libraries);
  const body = {
    note: 'Generated by scripts/superseded-clips.mjs - do not edit. Fingerprints of earlier bundled versions of built-in clips; a custom actions.json clip matching one is an unedited stale copy and follows the current bundled clip.',
    clips,
  };
  writeFileSync(`${root}/${OUT}`, `${JSON.stringify(body, null, 2)}\n`);
  const total = Object.values(clips).reduce((n, list) => n + list.length, 0);
  console.log(`${OUT}: ${total} superseded version(s) of ${Object.keys(clips).length} clip(s) from ${libraries.length} commit(s)`);
}
